import { environment } from 'environments/environment';

/**
 * Loads runtime configuration from `config.json` (generated by the Docker
 * entrypoint) and merges it into the {@link environment} object before Angular
 * bootstraps.
 *
 * This enables a single build artifact to be configured per environment at
 * container start time. Boolean-valued keys that arrive as strings (from shell
 * environment variables) are coerced to real booleans. When no `config.json`
 * is present or it cannot be read, the build-time defaults baked into
 * {@link environment} are kept.
 *
 * Must be awaited before the providers are constructed so that environment
 * derived injection tokens observe the merged values.
 */
export async function loadRuntimeConfig(): Promise<void> {
  try {
    const resp = await fetch(`${environment.baseHref}config.json`);
    if (!resp.ok) {
      return;
    }
    const config = (await resp.json()) as Record<string, unknown>;
    // Coerce boolean strings from env vars
    const booleanKeys: (keyof typeof environment)[] = [
      'production',
      'showUiSwitch',
      'aresBridgeEnabled',
      'useAlfrescoAPI',
    ];
    for (const key of booleanKeys) {
      if (key in config) {
        config[key] = config[key] === true || config[key] === 'true';
      }
    }
    Object.assign(environment, config);
  } catch {
    console.error('No runtime config.json found, using build-time defaults.');
  }
}
