/**
 * Describes a single language entry used across the application to render
 * language selectors, flags and localized labels.
 */
export interface LanguageCodeName {
  /** ISO 639-1 language code (e.g. `'en'`, `'fr'`, `'bg'`). */
  code: string;
  /**
   * Human-readable name of the language. Depending on the list it is either
   * the endonym (name of the language in that language) or the English name.
   */
  name: string;
  /** Emoji flag associated with the language (typically a country flag). */
  flag: string;
}

/**
 * The subset of languages the CIRCABC user interface is actually translated
 * into (the 24 official EU languages). Each entry uses its endonym as the
 * display `name`, making this list suitable for the UI language switcher.
 */
export const supportedLanguages: LanguageCodeName[] = [
  { code: 'bg', name: 'български', flag: '🇧🇬' },
  { code: 'cs', name: 'čeština', flag: '🇨🇿' },
  { code: 'da', name: 'dansk', flag: '🇩🇰' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'el', name: 'ελληνικά', flag: '🇬🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'et', name: 'eesti keel', flag: '🇪🇪' },
  { code: 'fi', name: 'Suomi', flag: '🇫🇮' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'ga', name: 'Gaeilge', flag: '🇮🇪' },
  { code: 'hr', name: 'hrvatski', flag: '🇭🇷' },
  { code: 'it', name: 'italiano', flag: '🇮🇹' },
  { code: 'lv', name: 'latviešu valoda', flag: '🇱🇻' },
  { code: 'lt', name: 'lietuvių kalba', flag: '🇱🇹' },
  { code: 'hu', name: 'magyar', flag: '🇭🇺' },
  { code: 'mt', name: 'Malti', flag: '🇲🇹' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'polski', flag: '🇵🇱' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ro', name: 'română', flag: '🇷🇴' },
  { code: 'sk', name: 'slovenčina', flag: '🇸🇰' },
  { code: 'sl', name: 'slovenščina', flag: '🇸🇮' },
  { code: 'sv', name: 'svenska', flag: '🇸🇪' },
];

/**
 * The full catalogue of languages that can be selected as content/metadata
 * languages, covering the EU languages plus a broad set of world languages.
 * Display names here are given in English, so this list is intended for
 * tagging or classifying content rather than for switching the UI locale.
 */
export const availableLanguages: LanguageCodeName[] = [
  { code: 'bg', name: 'Bulgarian', flag: '🇧🇬' },
  { code: 'cs', name: 'Czech', flag: '🇨🇿' },
  { code: 'da', name: 'Danish', flag: '🇩🇰' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'et', name: 'Estonian', flag: '🇪🇪' },
  { code: 'el', name: 'Greek', flag: '🇬🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'ga', name: 'Irish', flag: '🇮🇪' },
  { code: 'hr', name: 'Croatian', flag: '🇭🇷' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'lv', name: 'Latvian', flag: '🇱🇻' },
  { code: 'lt', name: 'Lithuanian', flag: '🇱🇹' },
  { code: 'hu', name: 'Hungarian', flag: '🇭🇺' },
  { code: 'mt', name: 'Maltese', flag: '🇲🇹' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'ro', name: 'Romanian', flag: '🇷🇴' },
  { code: 'sk', name: 'Slovak', flag: '🇸🇰' },
  { code: 'sl', name: 'Slovenian', flag: '🇸🇮' },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
  { code: 'aa', name: 'Afar', flag: '🇩🇯' },
  { code: 'ab', name: 'Abkhazian', flag: '🏳️' },
  { code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
  { code: 'ak', name: 'Akan', flag: '🇬🇭' },
  { code: 'sq', name: 'Albanian', flag: '🇦🇱' },
  { code: 'am', name: 'Amharic', flag: '🇪🇹' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
  { code: 'an', name: 'Aragonese', flag: '🇪🇸' },
  { code: 'hy', name: 'Armenian', flag: '🇦🇲' },
  { code: 'as', name: 'Assamese', flag: '🇮🇳' },
  { code: 'av', name: 'Avaric', flag: '🏳️' },
  { code: 'ae', name: 'Avestan', flag: '🏳️' },
  { code: 'ay', name: 'Aymara', flag: '🇧🇴' },
  { code: 'az', name: 'Azerbaijani', flag: '🇦🇿' },
  { code: 'ba', name: 'Bashkir', flag: '🇷🇺' },
  { code: 'bm', name: 'Bambara', flag: '🇲🇱' },
  { code: 'eu', name: 'Basque', flag: '🇪🇸' },
  { code: 'be', name: 'Belarusian', flag: '🇧🇾' },
  { code: 'bn', name: 'Bengali', flag: '🇧🇩' },
  { code: 'bh', name: 'Bihari', flag: '🇮🇳' },
  { code: 'bi', name: 'Bislama', flag: '🇻🇺' },
  { code: 'bs', name: 'Bosnian', flag: '🇧🇦' },
  { code: 'br', name: 'Breton', flag: '🇫🇷' },
  { code: 'my', name: 'Burmese', flag: '🇲🇲' },
  { code: 'ca', name: 'Catalan; Valencian', flag: '🇪🇸' },
  { code: 'ch', name: 'Chamorro', flag: '🇬🇺' },
  { code: 'ce', name: 'Chechen', flag: '🇷🇺' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { code: 'cu', name: 'Slavic', flag: '🏳️' },
  { code: 'cv', name: 'Chuvash', flag: '🇷🇺' },
  { code: 'kw', name: 'Cornish', flag: '🇬🇧' },
  { code: 'co', name: 'Corsican', flag: '🇫🇷' },
  { code: 'cr', name: 'Cree', flag: '🇨🇦' },
  { code: 'dv', name: 'Divehi; Dhivehi; Maldivian', flag: '🇲🇻' },
  { code: 'dz', name: 'Dzongkha', flag: '🇧🇹' },
  { code: 'eo', name: 'Esperanto', flag: '🏳️' },
  { code: 'ee', name: 'Ewe', flag: '🇬🇭' },
  { code: 'fo', name: 'Faroese', flag: '🇫🇴' },
  { code: 'fj', name: 'Fijian', flag: '🇫🇯' },
  { code: 'fy', name: 'Western Frisian', flag: '🇳🇱' },
  { code: 'ff', name: 'Fulah', flag: '🇬🇳' },
  { code: 'ka', name: 'Georgian', flag: '🇬🇪' },
  { code: 'gd', name: 'Gaelic', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { code: 'gl', name: 'Galician', flag: '🇪🇸' },
  { code: 'gv', name: 'Manx', flag: '🇮🇲' },
  { code: 'gn', name: 'Guarani', flag: '🇵🇾' },
  { code: 'gu', name: 'Gujarati', flag: '🇮🇳' },
  { code: 'ht', name: 'Haitian', flag: '🇭🇹' },
  { code: 'ha', name: 'Hausa', flag: '🇳🇬' },
  { code: 'he', name: 'Hebrew', flag: '🇮🇱' },
  { code: 'hz', name: 'Herero', flag: '🇳🇦' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
  { code: 'ho', name: 'Hiri Motu', flag: '🇵🇬' },
  { code: 'ig', name: 'Igbo', flag: '🇳🇬' },
  { code: 'is', name: 'Icelandic', flag: '🇮🇸' },
  { code: 'io', name: 'Ido', flag: '🏳️' },
  { code: 'ii', name: 'Sichuan Yi', flag: '🇨🇳' },
  { code: 'iu', name: 'Inuktitut', flag: '🇨🇦' },
  { code: 'ie', name: 'Interlingue', flag: '🏳️' },
  { code: 'ia', name: 'Interlingua', flag: '🏳️' },
  { code: 'id', name: 'Indonesian', flag: '🇮🇩' },
  { code: 'ik', name: 'Inupiaq', flag: '🇺🇸' },
  { code: 'jv', name: 'Javanese', flag: '🇮🇩' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'kl', name: 'Kalaallisut; Greenlandic', flag: '🇬🇱' },
  { code: 'kn', name: 'Kannada', flag: '🇮🇳' },
  { code: 'ks', name: 'Kashmiri', flag: '🇮🇳' },
  { code: 'kr', name: 'Kanuri', flag: '🇳🇬' },
  { code: 'kk', name: 'Kazakh', flag: '🇰🇿' },
  { code: 'km', name: 'Khmer', flag: '🇰🇭' },
  { code: 'ki', name: 'Kikuyu; Gikuyu', flag: '🇰🇪' },
  { code: 'rw', name: 'Kinyarwanda', flag: '🇷🇼' },
  { code: 'ky', name: 'Kirghiz', flag: '🇰🇬' },
  { code: 'kv', name: 'Komi', flag: '🇷🇺' },
  { code: 'kg', name: 'Kongo', flag: '🇨🇬' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'kj', name: 'Kuanyama; Kwanyama', flag: '🇳🇦' },
  { code: 'ku', name: 'Kurdish', flag: '🇮🇶' },
  { code: 'lo', name: 'Lao', flag: '🇱🇦' },
  { code: 'la', name: 'Latin', flag: '🏳️' },
  { code: 'li', name: 'Limburgan; Limburger; Limburgish', flag: '🇳🇱' },
  { code: 'ln', name: 'Lingala', flag: '🇨🇩' },
  { code: 'lb', name: 'Luxembourgish; Letzeburgesch', flag: '🇱🇺' },
  { code: 'lu', name: 'Luba-Katanga', flag: '🇨🇩' },
  { code: 'lg', name: 'Ganda', flag: '🇺🇬' },
  { code: 'mk', name: 'Macedonian', flag: '🇲🇰' },
  { code: 'mh', name: 'Marshallese', flag: '🇲🇭' },
  { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
  { code: 'mi', name: 'Maori', flag: '🇳🇿' },
  { code: 'mr', name: 'Marathi', flag: '🇮🇳' },
  { code: 'ms', name: 'Malay', flag: '🇲🇾' },
  { code: 'mg', name: 'Malagasy', flag: '🇲🇬' },
  { code: 'mo', name: 'Moldavian', flag: '🇲🇩' },
  { code: 'mn', name: 'Mongolian', flag: '🇲🇳' },
  { code: 'na', name: 'Nauru', flag: '🇳🇷' },
  { code: 'nv', name: 'Navajo; Navaho', flag: '🇺🇸' },
  { code: 'nr', name: 'South Ndebele', flag: '🇿🇦' },
  { code: 'nd', name: 'North Ndebele', flag: '🇿🇼' },
  { code: 'ng', name: 'Ndonga', flag: '🇳🇦' },
  { code: 'ne', name: 'Nepali', flag: '🇳🇵' },
  { code: 'nn', name: 'Norwegian Nynorsk', flag: '🇳🇴' },
  { code: 'nb', name: 'Norvégien Bokmål', flag: '🇳🇴' },
  { code: 'no', name: 'Norwegian', flag: '🇳🇴' },
  { code: 'ny', name: 'Chichewa; Chewa; Nyanja', flag: '🇲🇼' },
  { code: 'oc', name: 'Occitan (post 1500); Provençal', flag: '🇫🇷' },
  { code: 'oj', name: 'Ojibwa', flag: '🇨🇦' },
  { code: 'or', name: 'Oriya', flag: '🇮🇳' },
  { code: 'om', name: 'Oromo', flag: '🇪🇹' },
  { code: 'os', name: 'Ossetian; Ossetic', flag: '🇬🇪' },
  { code: 'pa', name: 'Panjabi; Punjabi', flag: '🇮🇳' },
  { code: 'fa', name: 'Persian', flag: '🇮🇷' },
  { code: 'pi', name: 'Pali', flag: '🏳️' },
  { code: 'ps', name: 'Pushto', flag: '🇦🇫' },
  { code: 'qu', name: 'Quechua', flag: '🇵🇪' },
  { code: 'rm', name: 'Raeto-Romance', flag: '🇨🇭' },
  { code: 'rn', name: 'Rundi', flag: '🇧🇮' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'sg', name: 'Sango', flag: '🇨🇫' },
  { code: 'sa', name: 'Sanskrit', flag: '🇮🇳' },
  { code: 'sr', name: 'Serbian', flag: '🇷🇸' },
  { code: 'si', name: 'Sinhala; Sinhalese', flag: '🇱🇰' },
  { code: 'se', name: 'Northern Sami', flag: '🇳🇴' },
  { code: 'sm', name: 'Samoan', flag: '🇼🇸' },
  { code: 'sn', name: 'Shona', flag: '🇿🇼' },
  { code: 'sd', name: 'Sindhi', flag: '🇵🇰' },
  { code: 'so', name: 'Somali', flag: '🇸🇴' },
  { code: 'st', name: 'Sotho, Southern', flag: '🇱🇸' },
  { code: 'sc', name: 'Sardinian', flag: '🇮🇹' },
  { code: 'ss', name: 'Swati', flag: '🇸🇿' },
  { code: 'su', name: 'Sundanese', flag: '🇮🇩' },
  { code: 'sw', name: 'Swahili', flag: '🇹🇿' },
  { code: 'ty', name: 'Tahitian', flag: '🇵🇫' },
  { code: 'ta', name: 'Tamil', flag: '🇮🇳' },
  { code: 'tt', name: 'Tatar', flag: '🇷🇺' },
  { code: 'te', name: 'Telugu', flag: '🇮🇳' },
  { code: 'tg', name: 'Tajik', flag: '🇹🇯' },
  { code: 'tl', name: 'Tagalog', flag: '🇵🇭' },
  { code: 'th', name: 'Thai', flag: '🇹🇭' },
  { code: 'bo', name: 'Tibetan', flag: '🇨🇳' },
  { code: 'ti', name: 'Tigrinya', flag: '🇪🇷' },
  { code: 'to', name: 'Tonga (Tonga Islands)', flag: '🇹🇴' },
  { code: 'tn', name: 'Tswana', flag: '🇧🇼' },
  { code: 'ts', name: 'Tsonga', flag: '🇿🇦' },
  { code: 'tk', name: 'Turkmen', flag: '🇹🇲' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
  { code: 'tw', name: 'Twi', flag: '🇬🇭' },
  { code: 'ug', name: 'Uighur; Uyghur', flag: '🇨🇳' },
  { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
  { code: 'ur', name: 'Urdu', flag: '🇵🇰' },
  { code: 'uz', name: 'Uzbek', flag: '🇺🇿' },
  { code: 've', name: 'Venda', flag: '🇿🇦' },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
  { code: 'vo', name: 'Volapük', flag: '🏳️' },
  { code: 'cy', name: 'Welsh', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'wa', name: 'Walloon', flag: '🇧🇪' },
  { code: 'wo', name: 'Wolof', flag: '🇸🇳' },
  { code: 'xh', name: 'Xhosa', flag: '🇿🇦' },
  { code: 'yi', name: 'Yiddish', flag: '🇮🇱' },
  { code: 'yo', name: 'Yoruba', flag: '🇳🇬' },
  { code: 'za', name: 'Zhuang; Chuang', flag: '🇨🇳' },
  { code: 'zu', name: 'Zulu', flag: '🇿🇦' },
];
