/**
 * ***************************************************************************** Copyright 2006
 * European Community
 *
 * <p>Licensed under the EUPL, Version 1.1 or - as soon they will be approved by the European
 * Commission - subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 *
 * <p>https://joinup.ec.europa.eu/software/page/eupl
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * ****************************************************************************
 */
package eu.europa.ec.digit.circabc.rest.service.log;

import io.swagger.model.LogRecord;
import io.swagger.model.LogRestRecord;
import io.swagger.model.db.ActivityCountDAO;
import io.swagger.model.db.LogActivityDAO;
import io.swagger.model.db.LogCountResultDAO;
import io.swagger.model.db.LogSearchResultDAO;
import io.swagger.model.db.UserActionLogDAO;
import io.swagger.model.db.UserNewsFeedRequest;
import java.util.Date;
import java.util.List;
import org.alfresco.service.cmr.repository.NodeRef;

// Logger

/**
 * Service abstraction for recording and querying CIRCABC activity logs.
 *
 * <p>Implementations persist audit/activity entries generated by user actions across the platform
 * (uploads, downloads, service accesses, REST calls, etc.) and expose read operations used to build
 * activity histories, user dashboards, news feeds and Interest Group statistics. The service covers
 * three broad responsibilities:
 *
 * <ul>
 *   <li><b>Writing</b> individual, batched and REST-specific log records.
 *   <li><b>Searching</b> and paginating logs, optionally filtered by Interest Group, user, service,
 *       action and date range.
 *   <li><b>Aggregating</b> activity data (counts, last-access/last-update timestamps, recent
 *       up/downloads) for reporting and dashboard features.
 * </ul>
 */
public interface LogService {
  /**
   * Persists a single activity log record.
   *
   * @param logRecord the record describing the action to be logged
   */
  void log(LogRecord logRecord);

  /**
   * Persists a single REST-specific log record capturing an HTTP REST API access.
   *
   * @param logRestRecord the REST log record to persist
   */
  void logRest(LogRestRecord logRestRecord);

  /**
   * Persists a batch of activity log records in a single operation.
   *
   * @param logRecords the list of records to persist
   */
  void logBatch(List<LogRecord> logRecords);

  /**
   * Returns the list of all distinct logged activities known to the system.
   *
   * @return the list of logged activities
   */
  List<LogActivityDAO> getActivities();

  /**
   * Returns the logged activities associated with a specific Interest Group.
   *
   * @param igID the database identifier of the Interest Group
   * @return the list of activities recorded for the given Interest Group
   */
  List<LogActivityDAO> getActivitiesById(long igID);

  /**
   * Searches log entries for an Interest Group, optionally filtered by user, service, action and
   * date range.
   *
   * @param igID the database identifier of the Interest Group whose logs are searched
   * @param user the username to filter by, or {@code null} for no user filter
   * @param service the service name to filter by, or {@code null} for no service filter
   * @param method the action/method name to filter by, or {@code null} for no action filter
   * @param fromDate the inclusive lower bound of the date range, or {@code null} for no lower bound
   * @param toDate the inclusive upper bound of the date range, or {@code null} for no upper bound
   * @return the matching log entries
   */
  List<LogSearchResultDAO> search(
    long igID,
    String user,
    String service,
    String method,
    Date fromDate,
    Date toDate
  );

  /**
   * Counts the log entries matching the given search filters, without materialising the results.
   *
   * @param igID the database identifier of the Interest Group whose logs are counted
   * @param user the username to filter by, or {@code null} for no user filter
   * @param service the service name to filter by, or {@code null} for no service filter
   * @param method the action/method name to filter by, or {@code null} for no action filter
   * @param fromDate the inclusive lower bound of the date range, or {@code null} for no lower bound
   * @param toDate the inclusive upper bound of the date range, or {@code null} for no upper bound
   * @return the number of matching log entries
   */
  int searchCount(
    long igID,
    String user,
    String service,
    String method,
    Date fromDate,
    Date toDate
  );

  /**
   * Returns a single page of log search results according to the supplied criteria.
   *
   * @param criteria the search criteria, including filters and pagination bounds
   * @return the log entries for the requested page
   */
  List<LogSearchResultDAO> searchPage(LogSearchCriteria criteria);

  /**
   * Returns the full action history for a specific content item.
   *
   * @param itemID the database identifier of the content item
   * @param uuid the Alfresco node UUID of the content item
   * @return the history entries for the item
   */
  List<LogSearchResultDAO> getHistory(long itemID, String uuid);

  /**
   * Counts the history entries recorded for a specific content item.
   *
   * @param itemID the database identifier of the content item
   * @param uuid the Alfresco node UUID of the content item
   * @return the number of history entries for the item
   */
  long countHistory(long itemID, String uuid);

  /**
   * Returns a paginated slice of the action history for a specific content item.
   *
   * @param itemID the database identifier of the content item
   * @param uuid the Alfresco node UUID of the content item
   * @param startRecord the zero-based index of the first record to return
   * @param pageSize the maximum number of records to return
   * @return the requested page of history entries
   */
  List<LogSearchResultDAO> getHistory(
    long itemID,
    String uuid,
    long startRecord,
    long pageSize
  );

  /**
   * Deletes all log entries belonging to the given Interest Group.
   *
   * @param igID the database identifier of the Interest Group whose logs are removed
   */
  void deleteInterestgroupLog(long igID);

  /**
   * Returns the date of the most recent login for the given user.
   *
   * @param username the username to look up
   * @return the last login date, or {@code null} if the user has never logged in
   */
  Date getLastLoginDateOfUser(String username);

  /**
   * Returns the number of logged actions for the previous day, grouped by hour.
   *
   * @return the per-hour action counts for yesterday
   */
  List<LogCountResultDAO> getNumberOfActionsYesterdayPerHour();

  /**
   * Returns per-activity counts for a given Interest Group, used for statistics reporting.
   *
   * @param igDbNode the database node identifier of the Interest Group
   * @return the list of activity counts for the Interest Group
   */
  List<ActivityCountDAO> getListOfActivityCountForInterestGroup(Long igDbNode);

  /**
   * Returns the date on which the given Interest Group was last accessed.
   *
   * @param igID the database identifier of the Interest Group
   * @return the last access date, or {@code null} if it has never been accessed
   */
  Date getLastAccessOnInterestGroup(long igID);

  /**
   * Returns the date on which the given Interest Group was last updated.
   *
   * @param igID the database identifier of the Interest Group
   * @return the last update date, or {@code null} if it has never been updated
   */
  Date getLastUpdateOnInterestGroup(long igID);

  /**
   * Returns the most recent downloads performed by the given user.
   *
   * @param userId the identifier of the user
   * @param i the maximum number of recent download entries to return
   * @return the recent download log entries
   */
  List<UserActionLogDAO> getRecentUserDownloads(String userId, int i);

  /**
   * Returns the most recent uploads performed by the given user.
   *
   * @param userId the identifier of the user
   * @param i the maximum number of recent upload entries to return
   * @return the recent upload log entries
   */
  List<UserActionLogDAO> getRecentUserUploads(String userId, int i);

  /**
   * Returns the identifiers of the activity types eligible for display on the user dashboard.
   *
   * @return the list of dashboard activity identifiers
   */
  List<Long> getUserDashboardActivityIds();

  /**
   * Returns the activity entries feeding the user dashboard / news feed for the given request.
   *
   * @param request the news-feed request describing the Interest Groups, activities and time window
   * @return the matching user activity entries
   */
  List<UserActionLogDAO> getUserDashboardActivities(
    UserNewsFeedRequest request
  );

  /**
   * Returns the identifiers of the Interest Groups visited by the given user, derived from REST
   * access logs.
   *
   * @param username the username to look up
   * @return the list of visited Interest Group identifiers
   */
  List<String> getVisitedIGRestLogs(String username);

  /**
   * Processes buffered REST log entries, typically converting or flushing them into persistent
   * activity logs. Intended to be invoked by a scheduled job.
   */
  void processRestLog();

  /**
   * Builds a {@link LogRecord} describing the upload of a file, ready to be persisted via {@link
   * #log(LogRecord)}.
   *
   * @param nodeRef the Alfresco node reference of the uploaded content
   * @param originalFileName the original name of the uploaded file
   * @return the prepared upload log record
   */
  LogRecord prepareLogUploadRequest(NodeRef nodeRef, String originalFileName);
}
