export interface LanguageCodeName {
  code: string;
  name: string;
}

export class SupportedLangs {
  public static availableLangs: LanguageCodeName[] = [
    { code: 'bg', name: 'български' },
    { code: 'cs', name: 'čeština' },
    { code: 'da', name: 'dansk' },
    { code: 'de', name: 'Deutsch' },
    { code: 'el', name: 'ελληνικά' },
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'et', name: 'eesti keel' },
    { code: 'fi', name: 'Suomi' },
    { code: 'fr', name: 'Français' },
    { code: 'ga', name: 'Gaeilge' },
    { code: 'hr', name: 'hrvatski' },
    { code: 'it', name: 'italiano' },
    { code: 'lv', name: 'latviešu valoda' },
    { code: 'lt', name: 'lietuvių kalba' },
    { code: 'hu', name: 'magyar' },
    { code: 'mt', name: 'Malti' },
    { code: 'nl', name: 'Nederlands' },
    { code: 'pl', name: 'polski' },
    { code: 'pt', name: 'Português' },
    { code: 'ro', name: 'română' },
    { code: 'sk', name: 'slovenčina' },
    { code: 'sl', name: 'slovenščina' },
    { code: 'sv', name: 'svenska' },
  ];
}

// eslint-disable-next-line max-classes-per-file
export class WorldLangs {
  public static availableLangs: LanguageCodeName[] = [
    { code: 'bg', name: 'Bulgarian' },
    { code: 'cs', name: 'Czech' },
    { code: 'da', name: 'Danish' },
    { code: 'de', name: 'German' },
    { code: 'et', name: 'Estonian' },
    { code: 'el', name: 'Greek' },
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Spanish' },
    { code: 'fr', name: 'French' },
    { code: 'ga', name: 'Irish' },
    { code: 'hr', name: 'Croatian' },
    { code: 'it', name: 'Italian' },
    { code: 'lv', name: 'Latvian' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'mt', name: 'Maltese' },
    { code: 'nl', name: 'Dutch' },
    { code: 'pl', name: 'Polish' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'ro', name: 'Romanian' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'fi', name: 'Finnish' },
    { code: 'sv', name: 'Swedish' },
    { code: 'aa', name: 'Afar' },
    { code: 'ab', name: 'Abkhazian' },
    { code: 'af', name: 'Afrikaans' },
    { code: 'ak', name: 'Akan' },
    { code: 'sq', name: 'Albanian' },
    { code: 'am', name: 'Amharic' },
    { code: 'ar', name: 'Arabic' },
    { code: 'an', name: 'Aragonese' },
    { code: 'hy', name: 'Armenian' },
    { code: 'as', name: 'Assamese' },
    { code: 'av', name: 'Avaric' },
    { code: 'ae', name: 'Avestan' },
    { code: 'ay', name: 'Aymara' },
    { code: 'az', name: 'Azerbaijani' },
    { code: 'ba', name: 'Bashkir' },
    { code: 'bm', name: 'Bambara' },
    { code: 'eu', name: 'Basque' },
    { code: 'be', name: 'Belarusian' },
    { code: 'bn', name: 'Bengali' },
    { code: 'bh', name: 'Bihari' },
    { code: 'bi', name: 'Bislama' },
    { code: 'bs', name: 'Bosnian' },
    { code: 'br', name: 'Breton' },
    { code: 'my', name: 'Burmese' },
    { code: 'ca', name: 'Catalan; Valencian' },
    { code: 'ch', name: 'Chamorro' },
    { code: 'ce', name: 'Chechen' },
    { code: 'zh', name: 'Chinese' },
    { code: 'cu', name: 'Slavic' },
    { code: 'cv', name: 'Chuvash' },
    { code: 'kw', name: 'Cornish' },
    { code: 'co', name: 'Corsican' },
    { code: 'cr', name: 'Cree' },
    { code: 'dv', name: 'Divehi; Dhivehi; Maldivian' },
    { code: 'dz', name: 'Dzongkha' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'ee', name: 'Ewe' },
    { code: 'fo', name: 'Faroese' },
    { code: 'fj', name: 'Fijian' },
    { code: 'fy', name: 'Western Frisian' },
    { code: 'ff', name: 'Fulah' },
    { code: 'ka', name: 'Georgian' },
    { code: 'gd', name: 'Gaelic' },
    { code: 'gl', name: 'Galician' },
    { code: 'gv', name: 'Manx' },
    { code: 'gn', name: 'Guarani' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'ht', name: 'Haitian' },
    { code: 'ha', name: 'Hausa' },
    { code: 'he', name: 'Hebrew' },
    { code: 'hz', name: 'Herero' },
    { code: 'hi', name: 'Hindi' },
    { code: 'ho', name: 'Hiri Motu' },
    { code: 'ig', name: 'Igbo' },
    { code: 'is', name: 'Icelandic' },
    { code: 'io', name: 'Ido' },
    { code: 'ii', name: 'Sichuan Yi' },
    { code: 'iu', name: 'Inuktitut' },
    { code: 'ie', name: 'Interlingue' },
    { code: 'ia', name: 'Interlingua' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ik', name: 'Inupiaq' },
    { code: 'jv', name: 'Javanese' },
    { code: 'ja', name: 'Japanese' },
    { code: 'kl', name: 'Kalaallisut; Greenlandic' },
    { code: 'kn', name: 'Kannada' },
    { code: 'ks', name: 'Kashmiri' },
    { code: 'kr', name: 'Kanuri' },
    { code: 'kk', name: 'Kazakh' },
    { code: 'km', name: 'Khmer' },
    { code: 'ki', name: 'Kikuyu; Gikuyu' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'ky', name: 'Kirghiz' },
    { code: 'kv', name: 'Komi' },
    { code: 'kg', name: 'Kongo' },
    { code: 'ko', name: 'Korean' },
    { code: 'kj', name: 'Kuanyama; Kwanyama' },
    { code: 'ku', name: 'Kurdish' },
    { code: 'lo', name: 'Lao' },
    { code: 'la', name: 'Latin' },
    { code: 'li', name: 'Limburgan; Limburger; Limburgish' },
    { code: 'ln', name: 'Lingala' },
    { code: 'lb', name: 'Luxembourgish; Letzeburgesch' },
    { code: 'lu', name: 'Luba-Katanga' },
    { code: 'lg', name: 'Ganda' },
    { code: 'mk', name: 'Macedonian' },
    { code: 'mh', name: 'Marshallese' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'mi', name: 'Maori' },
    { code: 'mr', name: 'Marathi' },
    { code: 'ms', name: 'Malay' },
    { code: 'mg', name: 'Malagasy' },
    { code: 'mo', name: 'Moldavian' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'na', name: 'Nauru' },
    { code: 'nv', name: 'Navajo; Navaho' },
    { code: 'nr', name: 'South Ndebele' },
    { code: 'nd', name: 'North Ndebele' },
    { code: 'ng', name: 'Ndonga' },
    { code: 'ne', name: 'Nepali' },
    { code: 'nn', name: 'Norwegian Nynorsk' },
    { code: 'nb', name: 'Norvégien Bokmål' },
    { code: 'no', name: 'Norwegian' },
    { code: 'ny', name: 'Chichewa; Chewa; Nyanja' },
    { code: 'oc', name: 'Occitan (post 1500); Provençal' },
    { code: 'oj', name: 'Ojibwa' },
    { code: 'or', name: 'Oriya' },
    { code: 'om', name: 'Oromo' },
    { code: 'os', name: 'Ossetian; Ossetic' },
    { code: 'pa', name: 'Panjabi; Punjabi' },
    { code: 'fa', name: 'Persian' },
    { code: 'pi', name: 'Pali' },
    { code: 'ps', name: 'Pushto' },
    { code: 'qu', name: 'Quechua' },
    { code: 'rm', name: 'Raeto-Romance' },
    { code: 'rn', name: 'Rundi' },
    { code: 'ru', name: 'Russian' },
    { code: 'sg', name: 'Sango' },
    { code: 'sa', name: 'Sanskrit' },
    { code: 'sr', name: 'Serbian' },
    { code: 'si', name: 'Sinhala; Sinhalese' },
    { code: 'se', name: 'Northern Sami' },
    { code: 'sm', name: 'Samoan' },
    { code: 'sn', name: 'Shona' },
    { code: 'sd', name: 'Sindhi' },
    { code: 'so', name: 'Somali' },
    { code: 'st', name: 'Sotho, Southern' },
    { code: 'sc', name: 'Sardinian' },
    { code: 'ss', name: 'Swati' },
    { code: 'su', name: 'Sundanese' },
    { code: 'sw', name: 'Swahili' },
    { code: 'ty', name: 'Tahitian' },
    { code: 'ta', name: 'Tamil' },
    { code: 'tt', name: 'Tatar' },
    { code: 'te', name: 'Telugu' },
    { code: 'tg', name: 'Tajik' },
    { code: 'tl', name: 'Tagalog' },
    { code: 'th', name: 'Thai' },
    { code: 'bo', name: 'Tibetan' },
    { code: 'ti', name: 'Tigrinya' },
    { code: 'to', name: 'Tonga (Tonga Islands)' },
    { code: 'tn', name: 'Tswana' },
    { code: 'ts', name: 'Tsonga' },
    { code: 'tk', name: 'Turkmen' },
    { code: 'tr', name: 'Turkish' },
    { code: 'tw', name: 'Twi' },
    { code: 'ug', name: 'Uighur; Uyghur' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'ur', name: 'Urdu' },
    { code: 'uz', name: 'Uzbek' },
    { code: 've', name: 'Venda' },
    { code: 'vi', name: 'Vietnamese' },
    { code: 'vo', name: 'Volapük' },
    { code: 'cy', name: 'Welsh' },
    { code: 'wa', name: 'Walloon' },
    { code: 'wo', name: 'Wolof' },
    { code: 'xh', name: 'Xhosa' },
    { code: 'yi', name: 'Yiddish' },
    { code: 'yo', name: 'Yoruba' },
    { code: 'za', name: 'Zhuang; Chuang' },
    { code: 'zu', name: 'Zulu' },
  ];
}
