version: "3"
services:
  db:
    container_name: db
    image: mysql:9.3.0
    ports:
      - "3306:3306"  
    environment:
        - MYSQL_ROOT_PASSWORD=password
    volumes:
        - mysql_data:/var/lib/mysql
        - mysql_init:/docker-entrypoint-initdb.d/:ro
    command: --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED
  tomcat:
    build: tomcat
    image: tomcat-circabc
    ports:
      - "81:8080"
      - "8889:8889"
    container_name: tomcat
    depends_on:
      - db

  solr:
    build: solr
    image: solr-circabc
    ports:
      - "84:8080"
    container_name: solr
    depends_on:
      - tomcat
  angular:
    build: angular
    image: angular-circabc
    ports:
        - "82:80"
    container_name: angular
    depends_on:
      - tomcat
  proxy: 
    image: nginx:alpine
    container_name: proxy-circabc
    depends_on:
      - angular
    volumes:
      - nginx_conf:/etc/nginx
    ports:
      - 80:80
      - 443:443
      - 14500:14500

volumes:
  nas0_contentstore:
  nas1_contentstore:
  nas2_contentstore:
  mysql_data:
  mysql_init:
    driver_opts:
      type: none
      o: bind
      device: ./mysql/init
  nginx_conf:
    driver_opts:
      type: none
      o: bind
      device: ./proxy/conf

