#     Copyright European Community 2006 - Licensed under the EUPL V.1.0
#
#  		   http://ec.europa.eu/idabc/en/document/6523
#

#
# CIRCABC general Settings
#
# These parameters are specifc to the target environment
# We can here override parameters located in circabc-global-settings.properties
#

# Web root url of alfresco
web.root.url=https://localhost/alfresco

# CircabcLoader properties
loader.filename=d:/export.txt
loader.error.filename=d:/users_imports/ErrorCIRCA_%s.txt

# Commision database  properties
dbloader.error.filename=d:/users_imports/ErrorCEC_%s.txt
dbloader.delete.filename=d:/users_imports/DelCEC_%s.txt

# Commision database  properties
dbloader.database.url=jdbc:oracle:thin:@localhost:1521:CIRCABC
dbloader.database.user=circabc
dbloader.database.password=changeme

# IPM integration
#ipm.baseurl=http://localhost:8081/ipmconf/remote/dispatch
#ipm.location=http://localhost:8081/ipmconf

# IPM Dev
ipm.baseurl=http://localhost:17121/ipm/remote/dispatch
ipm.location=http://localhost:17121/ipm
ipm.login=CircaIPM
ipm.password=changeme

# IAM webservice
iam.location=
iam.login=
iam.password=
#An email adress where to send error in we do not succed to call IAM service 
iam.error.email=

# LDAP Configuration
context.provider_url_ecas = ldap://localhost:11389/ou=AuthenticationDomains,o=cec.eu.int
context.provider_url = ldap://localhost:11389/ou=People,o=cec.eu.int
context.security_authentication=simple
context.security_principal=uid=CIRCABC,ou=TrustedApps,o=cec.eu.int
context.security_credentials=changeme

#EMAIL  Server Configuration for meeting responses
email_protocol = pop3
email_server = localhost
email_server_port=9110
email_box = INBOX
email_username =circabc
email_password =changeme
email_address=circabc@localhost
is_email_listener_active=false

#DISPLAY Server information
is_display_server_information_active=true

#VERSION INFO
version=V.4.2.0.0 - A 4.2.4 (.15)
#version=Trunk

#server node
node=N1

#bulk user ECAS departmentNumber
bulk.user.import.department.enabled=false
bulk.user.import.department.source=http://ipm.europa.eu/department/list

