#     Copyright European Community 2006 - Licensed under the EUPL V.1.0
#
#  		   http://ec.europa.eu/idabc/en/document/6523
#

#
# CIRCABC general Settings
#
# These parameters are specifc to the target environment
# We can here override parameters located in circabc-global-settings.properties
#

# Web root url of alfresco
web.root.url=https://localhost/alfresco

# CircabcLoader properties
loader.filename=d:/export.txt
loader.error.filename=d:/users_imports/ErrorCIRCA_%s.txt

# Commision database  properties
dbloader.error.filename=d:/users_imports/ErrorCEC_%s.txt
dbloader.delete.filename=d:/users_imports/DelCEC_%s.txt

# Commision database  properties
dbloader.database.url=jdbc:oracle:thin:@oraldg1.cc.cec.eu.int:1537:APPGRHP
dbloader.database.user=U_CRF4CIRCABC_P
dbloader.database.password=MyPa55word_

# IPM integration
#ipm.baseurl=http://applicationservers.cc.cec.eu.int:8081/ipmconf/remote/dispatch
#ipm.location=http://applicationservers.cc.cec.eu.int:8081/ipmconf

# PC Yanick
#ipm.baseurl=https://158.167.29.76:8443/ipm/remote/dispatch
#ipm.location=https://158.167.29.76:8443/ipm

# IPM Columba
#ipm.baseurl=https://columba.cc.cec.eu.int:8443/ipm/remote/dispatch
#ipm.location=https://columba.cc.cec.eu.int:8443/ipm

# IPM Atelier
#ipm.baseurl=https://158.167.34.42:8443/ipm/remote/dispatch
#ipm.location=https://158.167.34.42:8443/ipm

# IPM David Tomcat
#ipm.baseurl=http://D02DI0706037.net1.cec.eu.int:8081/ipm/remote/dispatch
#ipm.location=http://D02DI0706037.net1.cec.eu.int:8081/ipm

# IPM David Weblogic
#ipm.baseurl=http://D02DI0706037.net1.cec.eu.int:7001/ipm/remote/dispatch
#ipm.location=http://D02DI0706037.net1.cec.eu.int:7001/ipm

# IPM Dev
ipm.baseurl=http://wlsdev.cc.cec.eu.int:17121/ipm/remote/dispatch
ipm.location=http://wlsdev.cc.cec.eu.int:17121/ipm
ipm.login=CircaIPM
ipm.password=gxe825vpd9

# IAM webservice
iam.location=
iam.login=
iam.password=
#An email adress where to send error in we do not succed to call IAM service 
iam.error.email=

#EMAIL  Server Configuration for meeting responses
email_protocol = pop3
email_server = localhost
email_server_port=9110
email_box = INBOX
email_username =mrl
email_password =mrl
email_address=mrl@gmail.com
is_email_listener_active=false

#DISPLAY Server information
is_display_server_information_active=true

#VERSION INFO
version=V.4.2.0.0 - A 4.2.4 (.15)
#version=Trunk

#server node
node=N1

#bulk user ECAS departmentNumber
bulk.user.import.department.enabled=false
bulk.user.import.department.source=http://ipm.europa.eu/department/list

