import { Environment } from 'environments/environment.interface';

export const environment: Environment = {
  production: false,
  alfrescoURL: 'http://localhost:7001/service/api',
  circabcURL: 'http://localhost:7001/service/circabc',
  serverURL: 'http://localhost:7001/',
  alfrescoHost: 'http://localhost:7001',
  baseHref: '/ui/',
  nodeName: 'N1',
  showUiSwitch: false,
  environmentType: 'local',
  circabcRelease: 'oss',
  aresBridgeEnabled: false,
  aresBridgeServer: '',
  aresBridgeURL: '',
  aresBridgeKey: '',
  aresBridgeUiURL: '',
  analyticsURL: '',
  analyticsSiteId: '',
  analyticsInstance: '',
  officeClientId: '',
  shareURL: '',
  captchaURL: 'https://api.eucaptcha.eu',
  euloginUrl: 'http://localhost:7001/eulogin',
  eulogoutUrl: 'http://localhost:7001/eulogout',
  useAlfrescoAPI: false,
};
