import { Environment } from 'environments/environment.interface';

export const environment: Environment = {
  production: false,
  alfrescoURL: 'http://localhost:7001/service/api',
  circabcURL: 'http://localhost:7001/service/circabc',
  serverURL: 'http://localhost:7001/',
  alfrescoHost: 'http://localhost:7001',
  baseHref: '/ui/',
  nodeName: 'N1',
  showUiSwitch: false,
  environmentType: 'local',
  circabcRelease: 'ent',
  aresBridgeEnabled: false,
  aresBridgeServer: 'https://intragate.test.ec.europa.eu',
  aresBridgeURL: 'https://intragate.test.ec.europa.eu/Ares_pg/services/v1',
  aresBridgeKey: 'c4c750c74d8e44beb36e12ed9c8db2ab',
  aresBridgeUiURL: 'https://intragate.test.ec.europa.eu/Ares_pg/bridge/ui',
  analyticsURL: '',
  analyticsSiteId: '',
  analyticsInstance: '',
  officeClientId: '',
  shareURL: '',
  captchaURL: '../eucaptcha',
  euloginUrl: 'http://localhost:7001/eulogin',
  eulogoutUrl: 'http://localhost:7001/eulogout',
  useAlfrescoAPI: false,
  aiAgentUrl: 'http://localhost:8081',
};
