import { Environment } from 'environments/environment.interface';

export const environment: Environment = {
  production: false,
  alfrescoURL: 'http://localhost:7001/service/api',
  circabcURL: 'http://localhost:7001/service/circabc',
  serverURL: 'http://localhost:7001/',
  alfrescoHost: 'http://localhost:7001',
  baseHref: '/ui/',
  nodeName: 'N1',
  showUiSwitch: false,
  environmentType: 'local',
  circabcRelease: 'ent',
  aresBridgeEnabled: false,
  aresBridgeServer: '',
  aresBridgeURL: '',
  aresBridgeKey: '',
  aresBridgeUiURL: '',
  analyticsURL: 'localhost:4200',
  analyticsSiteId: 'fe2aaaa0-456a-44c0-a2d9-f7ef92d20d5d',
  analyticsInstance: 'testing',
  officeClientId: '',
  shareURL: '',
  captchaURL: 'https://circabc.acceptance.europa.eu/EuCaptcha-2.2.8',
  euloginUrl: 'http://localhost:7001/eulogin',
  eulogoutUrl: 'http://localhost:7001/eulogout',
  useAlfrescoAPI: false,
  aiAgentUrl: '',
};
