import { defineConfig } from 'cypress';

export default defineConfig({
  chromeWebSecurity: false,
  viewportWidth: 1200,
  viewportHeight: 860,
  defaultCommandTimeout: 24000,
  video:true,
  env: {
    host:'localhost',
    path:'/alfresco',
    port:8080,
    circabc_admin_create: true,
    timeout:500,
    runA11y:false,
    skipA11yFailures: true,
    logA11yFailures: true,
    'admin.username': 'admin',
    'admin.password': 'admin',
    'circabc.admin.username': 'CircabcAdmin',
    'circabc.admin.password': 'password123',
    'header.name': 'Test Header 1',
    'header.description': 'Test Header 1 description',
    'category.name': 'Test Category 1',
    'category.description': 'Test Category 1 description',
    'category.admin.username': 'CatAdmin1',
    'category.admin.password': 'password123',
    'category.admin.first.name': 'Category1',
    'category.admin.last.name': 'Admin',
    'category.admin.email': 'Category1.Admin@circabc.eu',
    'category.admin.phone': '123 123',
    'category.admin.postalAddress': 'unknown',
    'interest.group.name': 'Test IG',
    'interest.group.title': 'Test IG title',
    'interest.group.description': 'Test IG description',
    'interest.group.contact': 'Test IG contact',
    'interest.group.leader': 'IGadmin1',
    'interest.group.admin.username': 'IGadmin1',
    'interest.group.admin.password': 'password123',
    'interest.group.admin.first.name': 'Ig1',
    'interest.group.admin.last.name': 'Admin',
    'interest.group.admin.email': 'Ig1.admin@circabc.eu',
    'interest.group.admin.phone': '123 123',
    'interest.group.admin.postalAddress': 'unknown',
    'access.username': 'Access',
    'access.password': 'password123',
    'access.first.name': 'Access',
    'access.last.name': 'Access',
    'access.email': 'access@circabc.eu',
    'access.phone': '123 123',
    'access.postalAddress': 'unknown',
    'author.username': 'Author',
    'author.password': 'password123',
    'author.first.name': 'Author',
    'author.last.name': 'Author',
    'author.email': 'author@circabc.eu',
    'author.phone': '123 123',
    'author.postalAddress': 'unknown',
    'contributor.username': 'Contributor',
    'contributor.password': 'password123',
    'contributor.first.name': 'Contributor',
    'contributor.last.name': 'Contributor',
    'contributor.email': 'contributor@circabc.eu',
    'contributor.phone': '123 123',
    'contributor.postalAddress': 'unknown',
    'reviewer.username': 'Reviewer',
    'reviewer.password': 'password123',
    'reviewer.first.name': 'Reviewer',
    'reviewer.last.name': 'Reviewer',
    'reviewer.email': 'reviewer@circabc.eu',
    'reviewer.phone': '123 123',
    'reviewer.postalAddress': 'unknown',
    'secretary.username': 'Secretary',
    'secretary.password': 'password123',
    'secretary.first.name': 'Secretary',
    'secretary.last.name': 'Secretary',
    'secretary.email': 'secretary@circabc.eu',
    'secretary.phone': '123 123',
    'secretary.postalAddress': 'unknown',
    'help.section': 'Test help section',
  },
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.

    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.error(message);
          return null;
        },
      }),
      config.specPattern = [
        'cypress/e2e/circabc/home-page.spec.js',
        'cypress/e2e/circabc/login/login-page.spec.js',
        'cypress/e2e/circabc/logout/logout-page.spec.js',
        'cypress/e2e/circabc/user/create-page.spec.js',
        'cypress/e2e/circabc/circabc/create-page.spec.js',
        'cypress/e2e/circabc/header/create-page.spec.js',
        'cypress/e2e/circabc/category/create-page.spec.js',
        'cypress/e2e/circabc/category-logo/upload-logo-page.spec.js',
        'cypress/e2e/circabc/category-logo/select-logo-page.spec.js',
        'cypress/e2e/circabc/category-logo/delete-logo-page.spec.js',
        'cypress/e2e/circabc/interest-group/create-page.spec.js',
        'cypress/e2e/circabc/interest-group/delete-page.spec.js',
        'cypress/e2e/copy/interest-group/create-page.spec.js',
        'cypress/e2e/circabc/ig-request/ig-request-create-page.spec.js',
        'cypress/e2e/circabc/ig-request/ig-aprove-create-page.spec.js',
        'cypress/e2e/circabc/ig-request/ig-request-delete-page.spec.js',
        'cypress/e2e/circabc/ig-request/ig-aprove-delete-page.spec.js',
        'cypress/e2e/circabc/membership/go-to-membership-page.spec.js',
        'cypress/e2e/circabc/membership/invite-user-page.spec.js',
        'cypress/e2e/circabc/membership/update-membership-page.spec.js',
        'cypress/e2e/circabc/membership/delete-membership-page.spec.js',
        'cypress/e2e/circabc/interest-group/create-page.spec.js',
        'cypress/e2e/circabc/interest-group/test-ftp-page.spec.js',
        'cypress/e2e/circabc/library/go-to-library-page.spec.js',
        'cypress/e2e/circabc/library/notification-page.spec.js',
        'cypress/e2e/circabc/library/upload-page.spec.js',
        'cypress/e2e/circabc/library/download-page.spec.js',
        'cypress/e2e/circabc/check-in-out/check-out.spec.js',
        'cypress/e2e/circabc/check-in-out/check-in.spec.js',
        'cypress/e2e/copy/check-in-out/check-out.spec.js',
        'cypress/e2e/circabc/check-in-out/undo.spec.js',
        'cypress/e2e/circabc/library/copy-paste-page.spec.js',
        'cypress/e2e/circabc/library/create-space-page.spec.js',
        'cypress/e2e/circabc/library/set-favorite-space-page.spec.js',
        'cypress/e2e/circabc/library/importzip-page.spec.js',
        'cypress/e2e/circabc/library/delete-all-page.spec.js',
        'cypress/e2e/circabc/forum/create-page.spec.js',
        'cypress/e2e/circabc/help/section-create-page.spec.js',
        'cypress/e2e/circabc/help/section-update-page.spec.js',
        'cypress/e2e/circabc/help/link-create-page.spec.js',
        'cypress/e2e/circabc/help/link-update-page.spec.js',
        'cypress/e2e/circabc/help/search-page.spec.js',
        'cypress/e2e/circabc/help/link-delete-page.spec.js',
        'cypress/e2e/circabc/help/article-create-page.spec.js',
        'cypress/e2e/circabc/help/article-update-page.spec.js',
        'cypress/e2e/circabc/help/article-highlight-page.spec.js',
        'cypress/e2e/circabc/help/article-delete-page.spec.js',
        'cypress/e2e/circabc/help/section-delete-page.spec.js',
        'cypress/e2e/circabc/forum/delete-page.spec.js',
        'cypress/e2e/circabc/topic/create-page.spec.js',
        'cypress/e2e/circabc/topic/delete-page.spec.js',
        'cypress/e2e/circabc/system-message/create-page.spec.js',
        'cypress/e2e/circabc/system-message/update-page.spec.js',
        'cypress/e2e/circabc/system-message/delete-page.spec.js',
        'cypress/e2e/circabc/profile/create-page.spec.js',
        'cypress/e2e/circabc/profile/update-page.spec.js',
        'cypress/e2e/circabc/profile/delete-page.spec.js',
        'cypress/e2e/circabc/dynamic-authority/leader.spec.js',
        'cypress/e2e/circabc/dynamic-authority/owner.spec.js',
        'cypress/e2e/circabc/accessibility/accessibility.spec.js',
      ];
      return config;
    },
    baseUrl: 'http://localhost:4200/ui',
    specPattern: 'cypress/e2e/circabc/**/*.js',
  },
});
