-- USER SQL
CREATE USER circabc IDENTIFIED BY password
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
-- QUOTAS
ALTER USER circabc QUOTA UNLIMITED ON USERS;
-- ROLES
GRANT CONNECT, RESOURCE, DBA TO circabc;
-- SYSTEM PRIVILEGES

-- USER SQL
CREATE USER circabc_audit IDENTIFIED BY password
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
-- QUOTAS
ALTER USER circabc_audit QUOTA UNLIMITED ON USERS;
-- ROLES
GRANT CONNECT, RESOURCE, DBA TO circabc_audit;
-- SYSTEM PRIVILEGES

