dsname=CircabcDS
dsdbname=default;create=true
dsjndiname=jdbc/CircabcDS
dsdriver=oracle.jdbc.OracleDriver
dsurl=jdbc:oracle:thin:@oracle-db:1521/PDB1.localdomain
dsusername=circabc
dspassword=password
dstestquery=SQL ISVALID
dsmaxcapacity=1

