## This Alfresco Platform Configuration file should be used for custom properties that are introduced by this module.
## Define default values for all properties here.
## System Administrators can override these values in environment specific configurations in
## alfresco/tomcat/shared/classes/alfresco-global.properties.
## 
build.circabc.app.name=CIRCABC
# ent, oss or olaf
build.circabc.release=${BUILD_CIRCABC_RELEASE:oss}
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# for mysql mariadb use org.hibernate.dialect.MySQLDialect
# for oracle use org.hibernate.dialect.Oracle10gDialect

new.ui.url=${NEW_UI_URL:http://localhost:4200}
new.ui.context=${NEW_UI_CONTEXT:/ui/}

# Configuration parameter to use direct store access to Events instead of the search subsystem.
# It was added to avoid the delay that SOLR's eventual consistency caused.
# If set to false, is uses the original Lucene/SOLR search.
events.direct.store.access=${EVENTS_DIRECT_STORE_ACCESS:true}

email_address=
is_email_listener_active=${IS_EMAIL_LISTENER_ACTIVE:true}

#-------------------------#
# Email configuration     #
#-------------------------#
mail.enabled=${MAIL_ENABLED:false}
mail.host=${MAIL_HOST:maildev}
# Mail server configuration for sending
mail.protocol=${MAIL_PROTOCOL:smtp}
mail.port=${MAIL_PORT:1025}
mail.encoding=${MAIL_ENCODING:UTF-8}
mail.username=${MAIL_USERNAME:CIRCABC-LOCAL}
mail.password=${MAIL_PASSWORD:CIRCABC-LOCAL}
mail.from.default=${MAIL_FROM_DEFAULT:CIRCABC-LOCAL@localhost.test}
mail.smtp.debug=${MAIL_SMTP_DEBUG:true}
mail.redirect.email.address.enabled=${MAIL_REDIRECT_EMAIL_ADDRESS_ENABLED:false}
web.root.url=${WEB_ROOT_URL:http://localhost:8080/alfresco}
mail.disclamer.environment.consideration=${MAIL_DISCLAMER_ENVIRONMENT_CONSIDERATION:Please consider the environment before deciding to print this e-mail.}
mail.disclamer.content.support=This e-mail has been sent by the {2} application. If you have any question, feel free to use the <i>contact form</i> of {2}.
mail.disclamer.content.core=This e-mail and any attachments thereto may contain information which is confidential and/or protected by intellectual property \
rights and are intended for the sole use of the recipient(s) named above. Any use of the information contained herein (including, \
but not limited to, total or partial reproduction, communication or distribution in any form) by persons other than the designated \
recipient(s) is prohibited.
mail.disclamer.content.thanks=${MAIL_DISCLAMER_CONTENT_THANKS:Thank you for your cooperation.}

mail.disclamer.logo.cid=${MAIL_DISCLAMER_LOGO_CID:circabcLogo}
mail.disclamer.text="\n=======================================================\n${mail.disclamer.environment.consideration}\n\n${mail.disclamer.content.support}\n\n${mail.disclamer.content.core}\n${mail.disclamer.content.thanks}\n\n{1}";
mail.disclamer.html=<br /><hr /><b><i><span lang=\"EN\" style=\"font-size: 10pt; font-family: Georgia; color: green;\">${mail.disclamer.environment.consideration}</span></i></b><br /><br /><img align=\"left\" alt=\"CIRCABC logo\" src='cid:${mail.disclamer.logo.cid}' />${mail.disclamer.content.support}<br /><br />${mail.disclamer.content.core}<br />${mail.disclamer.content.thanks}<br /><br /><a title="CIRCABC home page" href=\"{1}\">{1}</a>

# Environment name to be added to the subject and body of emails being sent
# With this setting the users can know from which system the email came from
mail.environment.name.enabled=${MAIL_ENVIRONMENT_NAME_ENABLED:true}
mail.environment.name=${MAIL_ENVIRONMENT_NAME:CIRCABC LOCAL}

#-------------------------#
# ServiceNow API          #
#-------------------------#
service.now.enable=${SERVICE_NOW_ENABLE:true}
service.now.prefix=${SERVICE_NOW_PREFIX:true}
service.now.url=${SERVICE_NOW_URL:https://servicenow.example.org/api}
service.now.user=${SERVICE_NOW_USER:TO_BE_REPLACED_WITH_RIGHT_USER}
service.now.password=${SERVICE_NOW_PASSWORD:TO_BE_REPLACED_WITH_RIGHT_PASSWORD}

assignment_group=${SERVICE_NOW_ASSIGNMENT_GROUP:DIGIT CIRCABC Support}
business_service=${SERVICE_NOW_BUSINESS_SERVICE:CIRCABC service}
service_offering=${SERVICE_NOW_SERVICE_OFFERING:CIRCABC - General request}

proxy.enable=${PROXY_ENABLE:false}
proxy.url=${PROXY_URL:}
proxy.port=${PROXY_PORT:0}
proxy.username=${PROXY_USERNAME:}
proxy.password=${PROXY_PASSWORD:}

# EU captcha default URL
eu.captcha.url=${EU_CAPTCHA_URL:http://localhost:9898/eu-captcha}

# cache configuration

eu.cec.digit.circabc.cache.custom.logoImages.tx.maxItems=${CACHE_LOGOIMAGES_MAXITEMS:3000}
eu.cec.digit.circabc.cache.custom.logoConfig.tx.maxItems=${CACHE_LOGOCONFIG_MAXITEMS:3000}

eu.cec.digit.circabc.cache.custom.customizationContainer.tx.maxItems=${CACHE_CUSTOMIZATIONCONTAINER_MAXITEMS:3000}
eu.cec.digit.circabc.cache.custom.customizationContainerFolders.tx.maxItems=${CACHE_CUSTOMIZATIONCONTAINERFOLDERS_MAXITEMS:3000}

eu.europa.ec.digit.circabc.rest.service.user.ldapEcasDomainServiceCache.cluster.type=${CACHE_LDAPECAS_CLUSTER_TYPE:local}
eu.europa.ec.digit.circabc.rest.service.dynamic.property.dynamicPropertiesService.cluster.type=${CACHE_DYNAMICPROP_CLUSTER_TYPE:local}
eu.cec.digit.circabc.cache.custom.logoImages.cluster.type=${CACHE_LOGOIMAGES_CLUSTER_TYPE:local}
eu.cec.digit.circabc.cache.custom.logoConfig.cluster.type=${CACHE_LOGOCONFIG_CLUSTER_TYPE:local}
eu.cec.digit.circabc.cache.custom.customizationContainer.cluster.type=${CACHE_CUSTOMIZATIONCONTAINER_CLUSTER_TYPE:local}
eu.cec.digit.circabc.cache.custom.customizationContainerFolders.cluster.type=${CACHE_CUSTOMIZATIONCONTAINERFOLDERS_CLUSTER_TYPE:local}
#job properties


mail.from.circabc.helpdesk=${MAIL_FROM_CIRCABC_HELPDESK:EC-CENTRAL-HELPDESK@ec.europa.eu}
mail.from.circabc.it.helpdesk=${MAIL_FROM_CIRCABC_IT_HELPDESK:EC-HELPDESK-IT@ec.europa.eu}


# LDAP Configuration

context.initial_context_factory=${LDAP_CONTEXT_FACTORY:com.sun.jndi.ldap.LdapCtxFactory}
context.provider_url_ecas=${LDAP_PROVIDER_URL_ECAS:ldap://openldap:1389/ou=AuthenticationDomains,dc=example,dc=org}
context.provider_url=${LDAP_PROVIDER_URL:ldap://openldap:1389/ou=People,dc=example,dc=org}
context.security_authentication=${LDAP_SECURITY_AUTHENTICATION:simple}
context.security_principal=${LDAP_SECURITY_PRINCIPAL:cn=admin,dc=example,dc=org}
context.security_credentials=${LDAP_SECURITY_CREDENTIALS:changeit}

#machine translation delivery parameters
mt.enabled=${MT_ENABLED:false}
mt.protocol=${MT_PROTOCOL:ftp}
mt.user=${MT_USER:user}
mt.password=${MT_PASSWORD}
mt.host=${MT_HOST:host}
mt.port=${MT_PORT:1021}
mt.root.space=${MT_ROOT_SPACE:MT}
mt.application.name=${MT_APPLICATION_NAME:circabc}
mt.service.url=${MT_SERVICE_URL:https://webgate.ec.europa.eu/mtatecservices/public-services/translationService.wsdl}
mt.callback.url=${MT_CALLBACK_URL:http://localhost:8080/alfresco}

mt.rest.url=${MT_REST_URL:https://webgate.ec.europa.eu/etranslation/si/translate}
mt.rest.username=${MT_REST_USERNAME:circabc}
mt.rest.password=${MT_REST_PASSWORD}
# ECAS
authentication.chain=${AUTHENTICATION_CHAIN:alfrescoNtlm1:alfrescoNtlm}

# EU Login (ECAS) CAS Configuration
cas.baseUrl=${CAS_BASE_URL:https://ecas.ec.europa.eu/cas}
cas.serviceUrl=${CAS_SERVICE_URL:http://localhost:8080/alfresco/service/circabc/eulogin}
cas.frontendRedirectUrl=${CAS_FRONTEND_REDIRECT_URL:http://localhost:4200/ui/welcome}
cas.cookiePath=${CAS_COOKIE_PATH:/}

# Host name for the PDF preview rendition system. 
# If this property is not set, the hostname will be used instead
document.preview.render.host=${DOCUMENT_PREVIEW_RENDER_HOST:localhost}

# Allowed sizes for files (post attachments / logos for category, IG, avatar, etc.)
posts.allowed.attachment.size.bytes=${POSTS_ALLOWED_ATTACHMENT_SIZE_BYTES:1048576}
logo.allowed.size.bytes=${LOGO_ALLOWED_SIZE_BYTES:1048576}

# Define the name of the root temporary folder
business.temp.folder.name=${BUSINESS_TEMP_FOLDER_NAME:tempfiles}

# Define the time (millisecond) that a file can stay in the temp directory before cleanup.
# Since they are not many temp files created, this can be huge.
# We have to ensure that the user not longer need to access to it.
# 24 hours
business.temp.time.before.deletion=${BUSINESS_TEMP_TIME_BEFORE_DELETION:86400000}

app.autoupload.enabled.on.hostname=${APP_AUTOUPLOAD_ENABLED_ON_HOSTNAME:}

max.user.number=${MAX_USER_NUMBER:5}

iam.location=${IAM_LOCATION:}
iam.login=${IAM_LOGIN:}
iam.password=${IAM_PASSWORD:}
iam.error.email=${IAM_ERROR_EMAIL:}

### Jobs
log.job.enabled=${LOG_JOB_ENABLED:true}
circabc.global.statistics.enabled=${CIRCABC_GLOBAL_STATISTICS_ENABLED:true}
circabc.global.statistics.cron.expression=${CIRCABC_GLOBAL_STATISTICS_CRON_EXPRESSION:0 5 0 * * ?}
circabc.global.statistics.enabled.on.hostname=${CIRCABC_GLOBAL_STATISTICS_ENABLED_ON_HOSTNAME:}
app.autoupload.enabled=${APP_AUTOUPLOAD_ENABLED:true}

revocation.job.enabled=${REVOCATION_JOB_ENABLED:true}
clean.permission.job.enabled=${CLEAN_PERMISSION_JOB_ENABLED:true}
distribution.list.sender.job.enabled=${DISTRIBUTION_LIST_SENDER_JOB_ENABLED:true}

# EMAIL Server Configuration for meeting responses
email_protocol=${EMAIL_PROTOCOL:pop3}
email_server=${EMAIL_SERVER:localhost}
email_server_port=${EMAIL_SERVER_PORT:110}
email_box=${EMAIL_BOX:INBOX}
email_username=${EMAIL_USERNAME:CIRCABC-LOCAL}
email_password=${EMAIL_PASSWORD:CIRCABC-LOCAL}
email_address=${EMAIL_ADDRESS:CIRCABC-LOCAL@ec.europa.eu}
is_email_listener_active=${IS_EMAIL_LISTENER_ACTIVE:false}
is_email_use_tls=${IS_EMAIL_USE_TLS:true}

# maximum lock time in hours for a job , after entry in cbc_lcok table will be deleted 
unlock.job.enabled=${UNLOCK_JOB_ENABLED:true}
max.job.lock.time.in.hours=${MAX_JOB_LOCK_TIME_IN_HOURS:12}
# member exiration
member.expiration.job.enabled=${MEMBER_EXPIRATION_JOB_ENABLED:true}

#-------------------------#
# IG Import Configuration #
#-------------------------#
# Credentials for downloading content from the source CIRCABC instance during IG import
import.username=${IMPORT_USERNAME:admin}
import.password=${IMPORT_PASSWORD:}
